# Generated by Django 3.0.2 on 2020-08-17 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamentos', '0002_auto_20200817_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=60, verbose_name='Apellido')),
                ('job', models.CharField(choices=[('0', 'CONTADOR'), ('1', 'ADMINISTRATIVO'), ('2', 'ECONOMISTA'), ('3', 'OTRO')], max_length=30, verbose_name='Puesto')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.Departamento')),
            ],
        ),
    ]
