# Generated by Django 3.0.2 on 2020-08-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='habilidad',
            field=models.ManyToManyField(to='personas.Habilidades'),
        ),
    ]
