# Generated by Django 3.0.2 on 2020-08-20 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_auto_20200820_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleados',
            old_name='hoja_de_visa',
            new_name='hoja_de_vida',
        ),
    ]
