# Generated by Django 3.0.2 on 2020-11-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_empleados_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='Avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado', verbose_name='Foto'),
        ),
    ]
